name: Build macOS App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set Xcode Version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Build
      run: |
        xcodebuild clean build \
          -project ClipboardMonitor.xcodeproj \
          -scheme ClipboardMonitor \
          -configuration Release \
          -derivedDataPath build \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO
    
    - name: Create DMG
      run: |
        # 创建临时目录
        mkdir -p tmp/dmg
        # 复制应用到临时目录
        cp -r build/Build/Products/Release/ClipboardMonitor.app tmp/dmg/
        # 创建 DMG
        hdiutil create -volname "ClipboardMonitor" \
          -srcfolder tmp/dmg \
          -ov -format UDZO \
          ClipboardMonitor.dmg
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ClipboardMonitor
        path: ClipboardMonitor.dmg 